## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  - APP-FUNC-TEST
  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-gcp/script/utils"

## Setup the kubernetes cluster

gcp-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP
  script: 
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

## Setup OpenEBS control plane

openebs-gcp-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - gcp-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

openebs-sc-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - gcp-cluster
  script:
   - chmod 775 ./script/provider/setup-sc
   - ./script/provider/setup-sc
  artifacts:
    paths:
      - .kube-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-gcp-deploy

## Define the app deployer jobs

# PERCONA-JIVA
percona-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-jiva

percona-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/jiva/percona-app-workload-jiva

# MONGO-JIVA
mongo-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/mongo/deployer/mongo-app-deploy-jiva

mongo-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/mongo/workload/jiva/mongo-app-workload-jiva

POSTGRES-JIVA
postgres-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/postgres/deployer/postgres-app-deploy-jiva

postgres-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/postgres/workload/jiva/postgres-app-workload-jiva

CASSANDRA-JIVA
cassandra-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/cassandra/deployer/cassandra-app-deploy-jiva

cassandra-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/cassandra/workload/jiva/cassandra-app-workload-jiva

JENKINS-JIVA
jenkins-jiva-run/load/check:
  extends: .app_deploy_template
  script: 
   - ./script/apps/jenkins/deployer/jenkins-app-deploy-jiva

# PERCONA-CSTOR
percona-cstor-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-cstor

percona-cstor-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-workload-cstor

MONGO-CSTOR
mongo-cstor-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/mongo/deployer/mongo-app-deploy-cstor

mongo-cstor-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/mongo/workload/cstor/mongo-app-workload-cstor

     ## CASSANDRA_CSTOR
     #cassandra-cstor-run/load/check 0:2:
     #  extends: .app_deploy_template
     #  script:
     #   - ./script/apps/cassandra/deployer/cassandra-app-deploy-cstor
     #
     #cassandra-cstor-run/load/check 1:2:
     #  extends: .app_deploy_template
     #  before_script:
     #   - sleep 180
     #  script:
     #   - ./script/apps/cassandra/workload/cstor/cassandra-app-workload-cstor
     #
     ## JENKINS_CSTOR
     #jenkins-cstor-run/load/check:
     #  extends: .app_deploy_template
     #  script:
     #   - ./script/apps/jenkins/deployer/jenkins-app-deploy-cstor 
     #
     ## PROMETHEUS-CSTOR
     #prometheus-cstor-run/load/check:
     #  extends: .app_deploy_template
     #  script:
     #   - ./script/apps/prometheus/deployer/prometheus-app-deploy-cstor

## Define job template for func test jobs  

.func_test_template:
  image: atulabhi/kops:v8
  stage: APP-FUNC-TEST
  when: always 

app-replica-scale-{cassandra-jiva}:
  extends: .func_test_template #dependencies: cassandra-jiva
  script:
   - ./script/apps/cassandra/functional/jiva/app-sts-replica-scale 

app-upgrade-deployment-{jenkins-jiva}:
  extends: .func_test_template #dependencies: jenkins-jiva
  script:
   - ./script/apps/jenkins/functional/jiva/app-upgrade-deployment

volume-data-integrity-{fio-jiva}:
  extends: .func_test_template 
  script:
   - ./script/apps/fio/tests/jiva/fio-volume-data-integrity-check

     #volume-data-integrity-{fio-cstor}:
     #  extends: .func_test_template
     #  script: 
     #   - ./script/apps/fio/tests/cstor/fio-volume-data-integrity-check

k8s-snapshot-clone-creation-{percona-jiva}:
  extends: .func_test_template
  script:
   - ./script/apps/percona/functional/jiva/k8s-snapshot-clone

Snapshot-rebuild-single-replica-{percona-cstor}:
  extends: .func_test_template
  script:
   - ./script/apps/percona/functional/cstor/snapshot-rebuild-single-rep
   
Snapshot-rebuild-multiple-replica-{percona-cstor}:
  extends: .func_test_template
  script:
   - ./script/apps/percona/functional/cstor/snapshot-rebuild-multiple-rep  

     #jiva-replica-scaleup-{percona-jiva}:
     #  extends: .func_test_template
     #  script:
     #   - ./script/apps/percona/functional/jiva/jiva-replica-scaleup   
   
volume-memory-consumption-{memcheck-jiva}:
  extends: .func_test_template
  script:
   - ./script/apps/memleak/tests/jiva/memory-consumption

     #app-replica-scale-{cassandra-cstor}:
     #  extends: .func_test_template #dependencies: cassandra-cstor
     #  script:
     #   - ./script/apps/cassandra/functional/cstor/app-sts-replica-scale
     #
     #app-upgrade-deployment-{jenkins-cstor}:
     #  extends: .func_test_template #dependencies: jenkins-cstor
     #  script:
     #   - ./script/apps/jenkins/functional/cstor/app-upgrade-deployment
     #
     #volume-memory-consumption-{memcheck-cstor}: #dependencies: prometheus-cstor
     #  extends: .func_test_template
     #  script:
     #   - chmod 775 ./script/apps/prometheus/functional/cstor/memcheck/memory-consumption
     #   - ./script/apps/prometheus/functional/cstor/memcheck/memory-consumption

# Define job template for chaos jobs 

.chaos_test_template:
  image: atulabhi/kops:v8
  stage: APP-CHAOS-TEST
  when: always 

repl-kill-{percona-jiva}:
  extends: .chaos_test_template #dependencies: percona-jiva
  script:
   - ./script/apps/percona/chaos/jiva/volume-replica-failure

ctrl-kill-{mongo-jiva}:
  extends: .chaos_test_template #dependencies: mongo-jiva
  script:
   - ./script/apps/mongo/chaos/jiva/volume-controller-failure

repl-disconnect-{jenkins-jiva}:
  extends: .chaos_test_template #dependencies: jenkins-jiva
  script:
   - ./script/apps/jenkins/chaos/jiva/volume-replica-network-delay

ctrl-disconnect-{postgres-jiva}:
  extends: .chaos_test_template #dependencies: postgres-jiva
  script:
   - ./script/apps/postgres/chaos/jiva/volume-controller-network-delay

     #app-kill-{mongo-jiva-xfs}:
     #  extends: .chaos_test_template #dependencies: mongo-jiva
     #  script:
     #   - ./script/apps/mongo/chaos/jiva/application-pod-failure
     #
     #app-kill-{jenkins-cstor}:
     #  extends: .chaos_test_template #dependencies: jenkins-cstor
     #  script:
     #   - ./script/apps/jenkins/chaos/cstor/application-pod-failure

tgt-kill-{percona-cstor}:
  extends: .chaos_test_template #dependencies: percona-cstor
  script:
   - ./script/apps/percona/chaos/cstor/volume-target-failure

tgt-disconnect-{mongo-cstor}:
  extends: .chaos_test_template #dependencies: mongo-cstor
  script:
   - ./script/apps/mongo/chaos/cstor/volume-target-network-delay

cleanup-gcp:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/gcp-cleanup
    - ./script/gcp-cleanup
