## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-gcp/script/utils"

## Setup the kubernetes cluster

gcp-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP
  script: 
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

## Setup OpenEBS control plane

openebs-gcp-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - gcp-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

openebs-sc-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - gcp-cluster
  script:
   - chmod 775 ./script/provider/setup-sc
   - ./script/provider/setup-sc
  artifacts:
    paths:
      - .kube-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-gcp-deploy

# NUODB-CSTOR
nuodb-cstor-run/load:
  extends: .app_deploy_template
  script:
   - ./script/apps/nuodb/deployer/nuodb-app-deploy-cstor

## Define the app deployer jobs
cleanup-gcp:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/gcp-cleanup
    - ./script/gcp-cleanup
